### ISSUE TITLE
The link can't be opened

### ISSUE THREAD

**Issue by huidemie** [malllabiisc/EWISE#7]
hello, this link : http://lcl.uniroma1.it/wsdeval/data/WSD_Evaluation_Framework.zip  can not be opened. How can I download the evaluation framework? Thank you.

**Comment by SawanKumar28** [comment]
Could be temporarily down. You could contact the authors of the paper in case it continues to be so.
The paper which introduces the framework:
https://www.aclweb.org/anthology/E17-1010/

**Comment by SawanKumar28** [comment]
The link is working. Closing the issue.
